CREATE TABLE USERS (
    UserID VARCHAR2(255),
    Password VARCHAR2(255) NOT NULL,
    Name VARCHAR2(255) NOT NULL,
    Balance NUMBER(15) DEFAULT 0 NOT NULL,
    Tier VARCHAR2(50)
);

CREATE TABLE CATEGORY (
    CategoryID NUMBER,
    Name VARCHAR2(255) NOT NULL
);

CREATE TABLE ITEM (
    ItemID NUMBER,
    Name VARCHAR2(255) NOT NULL,
    Description CLOB,
    BasePrice NUMBER(15) NOT NULL,
    CategoryID NUMBER
);

CREATE TABLE INVENTORY (
    InventoryID NUMBER,
    UserID VARCHAR2(255) NOT NULL,
    ItemID NUMBER NOT NULL,
    Quantity NUMBER DEFAULT 1 NOT NULL,
    Conditions VARCHAR2(255),
    Acquired_Date TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE AUCTION (
    AuctionID NUMBER,
    Start_Price NUMBER(15) NOT NULL,
    StartTime TIMESTAMP NOT NULL,
    EndTime TIMESTAMP NOT NULL,
    CurrentHighestPrice NUMBER(15),
    ItemID NUMBER NOT NULL,
    SellerID VARCHAR2(255),
    registerinventoryID NUMBER NOT NULL
);

CREATE TABLE BIDDING_RECORD (
    AuctionID NUMBER,
    BidderID VARCHAR2(255),
    BidTime TIMESTAMP,
    BidAmount NUMBER(15) NOT NULL
);

CREATE TABLE TRANSACTION (
    TradeID NUMBER,
    AuctionID NUMBER NOT NULL,
    SellerID VARCHAR2(255) NOT NULL,
    BuyerID VARCHAR2(255) NOT NULL,
    TradeTime TIMESTAMP NOT NULL,
    Final_Price NUMBER(15) NOT NULL,
    Commission NUMBER(15) NOT NULL
);

CREATE TABLE FAVORITE (
    UserID VARCHAR2(255),
    AuctionID NUMBER,
    AddedTime TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE MARKET_HISTORY (
    HistoryID NUMBER,
    AuctionID NUMBER NOT NULL,
    FinalPrice NUMBER(15) NOT NULL,
    TradeTime TIMESTAMP NOT NULL
);

ALTER TABLE USERS ADD CONSTRAINT pk_users PRIMARY KEY (UserID);
ALTER TABLE CATEGORY ADD CONSTRAINT pk_category PRIMARY KEY (CategoryID);
ALTER TABLE ITEM ADD CONSTRAINT pk_item PRIMARY KEY (ItemID);
ALTER TABLE INVENTORY ADD CONSTRAINT pk_inventory PRIMARY KEY (InventoryID);
ALTER TABLE AUCTION ADD CONSTRAINT pk_auction PRIMARY KEY (AuctionID);
ALTER TABLE BIDDING_RECORD ADD CONSTRAINT pk_bidding_record PRIMARY KEY (AuctionID, BidderID, BidTime);
ALTER TABLE TRANSACTION ADD CONSTRAINT pk_transaction PRIMARY KEY (TradeID);
ALTER TABLE FAVORITE ADD CONSTRAINT pk_favorite PRIMARY KEY (UserID, AuctionID);
ALTER TABLE MARKET_HISTORY ADD CONSTRAINT pk_market_history PRIMARY KEY (HistoryID);

ALTER TABLE CATEGORY ADD CONSTRAINT uq_category_name UNIQUE (Name);
ALTER TABLE INVENTORY ADD CONSTRAINT uq_user_item UNIQUE (UserID, ItemID);
ALTER TABLE TRANSACTION ADD CONSTRAINT uq_trans_auction UNIQUE (AuctionID);
ALTER TABLE MARKET_HISTORY ADD CONSTRAINT uq_hist_auction UNIQUE (AuctionID);

ALTER TABLE ITEM ADD CONSTRAINT fk_item_category FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID);
ALTER TABLE INVENTORY ADD CONSTRAINT fk_inventory_user FOREIGN KEY (UserID) REFERENCES USERS(UserID) ON DELETE CASCADE;
ALTER TABLE INVENTORY ADD CONSTRAINT fk_inventory_item FOREIGN KEY (ItemID) REFERENCES ITEM(ItemID) ON DELETE CASCADE;
ALTER TABLE AUCTION ADD CONSTRAINT fk_auction_item FOREIGN KEY (ItemID) REFERENCES ITEM(ItemID);
ALTER TABLE AUCTION ADD CONSTRAINT fk_auction_seller FOREIGN KEY (SellerID) REFERENCES USERS(UserID) ON DELETE CASCADE;
ALTER TABLE BIDDING_RECORD ADD CONSTRAINT fk_bidding_auction FOREIGN KEY (AuctionID) REFERENCES AUCTION(AuctionID) ON DELETE CASCADE;
ALTER TABLE BIDDING_RECORD ADD CONSTRAINT fk_bidding_user FOREIGN KEY (BidderID) REFERENCES USERS(UserID);
ALTER TABLE TRANSACTION ADD CONSTRAINT fk_trans_auction FOREIGN KEY (AuctionID) REFERENCES AUCTION(AuctionID);
ALTER TABLE TRANSACTION ADD CONSTRAINT fk_trans_seller FOREIGN KEY (SellerID) REFERENCES USERS(UserID);
ALTER TABLE TRANSACTION ADD CONSTRAINT fk_trans_buyer FOREIGN KEY (BuyerID) REFERENCES USERS(UserID);
ALTER TABLE FAVORITE ADD CONSTRAINT fk_fav_user FOREIGN KEY (UserID) REFERENCES USERS(UserID) ON DELETE CASCADE;
ALTER TABLE FAVORITE ADD CONSTRAINT fk_fav_auction FOREIGN KEY (AuctionID) REFERENCES AUCTION(AuctionID) ON DELETE CASCADE;
ALTER TABLE MARKET_HISTORY ADD CONSTRAINT fk_history_auction FOREIGN KEY (AuctionID) REFERENCES AUCTION(AuctionID);

CREATE SEQUENCE seq_transaction_id
START WITH 5000
INCREMENT BY 1;

CREATE SEQUENCE INVENTORY_SEQ
START WITH 501
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE USERS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE BID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE MARKET_HISTORY_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE AUCTION_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

ALTER TABLE AUCTION ADD ReceivedFlag NUMBER DEFAULT 0;
UPDATE AUCTION SET ReceivedFlag = 0 WHERE ReceivedFlag IS NULL;

ALTER TABLE AUCTION ADD CONSTRAINT CHK_RECEIVEDFLAG CHECK (ReceivedFlag IN (0,1));

ALTER TABLE AUCTION MODIFY RegisterInventoryID NULL;

COMMIT;
